### PR TITLE
test_geeglm

### PR DESCRIPTION
**Pull request by jzangela**
Hi James,

Here are some notes on the current state of the test_geeglm file.

1. userdefined model: genZcor function generate output with attributes at the end, nrow is not correct, cannot be used in geeglm. Maybe check the data generation process.
2. "bread works": not for the unstructured correlation model
3. add check.attributes = F to expect_equal, need to confirm
4. vcovCR for geeglm is using bread function from sandwich package, need to confirm
5. "vcovCR works for clustering variables higher than id variable." & "Order doesn't matter." have problems, maybe related.
6. "clubSandwich works with dropped observations" has problems.

I listed all the things that are not working and I will try more on the first point (userdefined model) since it is more of a thing to be fixed with our use of the geepack rather than the actual test for clubSandwich. Would appreciate hints on any of these points.

Thanks for diagnosing! 

Best regards,
Jingru

### CODE REVIEW

**Comment by jepusto** [comment]
Hi Jingru, 

I was fiddling with this stuff a little bit this afternoon. Here are a few notes:

> 1. userdefined model: genZcor function generate output with attributes at the end, nrow is not correct, cannot be used in geeglm. Maybe check the data generation process.

I think I've got this fixed now. I also added a model with userdefined zcor based on a Toeplitz structure and a model with a fixed correlation structure..

> 2. "bread works": not for the unstructured correlation model

I think it's working now.

> 3. add check.attributes = F to expect_equal, need to confirm

Based on `?expect_equivalent`, the recommended form for this is `expect_equal(..., ignore_attr = TRUE)`.
 
> 4. vcovCR for geeglm is using bread function from sandwich package, need to confirm

It looks like `sandwich::bread()` will call `clubSandwich::bread.geeglm()`, which is what we need it to do.

> 5. "vcovCR works for clustering variables higher than id variable." & "Order doesn't matter." have problems, maybe related.

The problem here seems to be that `targetVariance.geegelm()` and `weightMatrix.geeglm()` always return matrix-lists with the `obj$id` as the clustering variable (i.e., one matrix for each level of `obj$id`). In cases where `obj$id != cluster`, we need these functions to return matrix-lists based on the user-specified clustering variable. I think you could do this by 1) checking whether `obj$id` is identical/equivalent to `cluster` and 2) if not, use `clubSandwich::nest_bdiag()` to coerce the targetVariance result or weightMatrix result into the right form.

> 6. "clubSandwich works with dropped observations" has problems.

I'm not sure what the problem is here yet.

**Comment by jzangela** [comment]
Hi James,

I tried some updates on the higher-order clustering for geeglm and here are some notes. In the current test, the "vcovCR works for clustering variables higher than the id variable" test includes both tests for "higher-order clustering" and "order doesn't matter for the cluster variables". It seems that the test for higher order clustering passes, but for scrambled order the test does not. Would appreciate it if you have any suggestions. Thanks!

Best regards,
Jingru

**Review by jepusto — APPROVED** [review]

**Comment by jepusto** [comment]
There's some sort of namespace issue with the unit tests for `geeglm()` with `corstr = "userdefined"` or `corstr = "fixed"`. The tests pass just fine when run interactively, but when run through `devtools::test()` the `zcor` objects aren't found. I'm not sure what's happening, but it seems to be a problem with the tests rather than with the methods for `geeglm` objects themselves.

**Comment by jzangela** [comment]
Thanks, James! I will check the namespace issue out and keep you posted if I find anything.

**Comment by jzangela** [comment]
Terrific! Thanks, James! Looks like we combined the "userdefined" and "fixed" cor matrix in a same group. And we deleted them in the test file for scrambled order tests?

**Comment by jepusto** [comment]
> Terrific! Thanks, James! Looks like we combined the "userdefined" and "fixed" cor matrix in a same group. And we deleted them in the test file for scrambled order tests?

The main change is in lines 130-135 of `R/geeglm.R`, which provides a little extra help locating the environment where the function can find the `zcor` argument of the geeglm object. Removing the userdefined and fixed examples from the scrambled order tests was just because I felt like they were overkill/unnecessary.

**Comment by jzangela** [comment]
Thanks for the explanation, James!

**Pull request merged**
